development:
  adapter: mysql2
  encoding: utf8
  database: ey_sample_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: ey_sample_test
  pool: 5
  username: root
  password:
  encoding: utf8
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: ey_sample_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
