development:
  adapter: mysql
  encoding: utf8
  database: ey_sample_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: ey_sample_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: ey_sample_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
